apiVersion: v1
kind: Namespace
metadata:
  name: dangerous-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: pods-with-vulnerabilities
  namespace: dangerous-namespace
spec:
  containers:
  - name: old-nginx
    image: nginx:1.19
