apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-server
  labels:
    app: trivy-server
#imagePullSecrets:
#  - name: robotregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server-deployment
  labels:
    app: trivy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      serviceAccountName: trivy-server
      containers:
      - name: trivy-server
        image: ghcr.io/aquasecurity/trivy:0.18.3
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        command :
        - trivy
        - server
        - --listen
        - 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivy-server
  name: trivy-server
spec:
  type: ClusterIP
  selector:
    app: trivy-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivy-server
  labels:
    app: trivy-server
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: fabrice-ca-issuer
spec:
  rules:
  - host: trivy.tools.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trivy-server
            port: 
               number: 8080
  tls:
  - hosts:
    - trivy.tools.local
    secretName: trivy-server-ingress-tls-secret
