apiVersion: v1
kind: Namespace
metadata:
  name: trivy-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-server
  namespace: trivy-server
  labels:
    app: trivy-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server-deployment
  namespace: trivy-server
  labels:
    app: trivy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-server
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      serviceAccountName: trivy-server
      containers:
      - name: trivy-server
        image: ghcr.io/aquasecurity/trivy:0.18.3
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        command :
        - trivy
        - server
        - --listen
        - 0.0.0.0:8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: trivy-server
  labels:
    app: trivy-server
  name: trivy-server
spec:
  type: ClusterIP
  selector:
    app: trivy-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
