{
 "title": "Trivy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Critical Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"critical\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "High Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"high\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Medium Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"medium\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Low Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"low\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Cluster Vulnerabilities Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=~\"critical|high\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Namespaces With Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "namespace_vulnerabilities_total{severity=\"critical\"}>0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespaces With High Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "namespace_vulnerabilities_total{severity=\"high\"}>0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Images With Critical Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "image_vulnerabilities_total{severity=\"critical\"}>0",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Images With High Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "image_vulnerabilities_total{severity=\"high\"}>0",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}